/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function (Backbone, Drupal) {
  Drupal.cartFlyout.CartOffcanvasView = Backbone.View.extend({
    initialize: function initialize() {
      this.listenTo(this.model, 'cartsLoaded', this.render);
    },

    events: {
      'click .cart-block--offcanvas-cart-table__remove button': 'removeItem'
    },
    removeItem: function removeItem(e) {
      var target = JSON.parse(e.target.value);
      var endpoint = Drupal.url('cart/' + target[0] + '/items/' + target[1] + '?_format=json');
      fetch(endpoint, {
        credentials: 'include',
        method: 'delete'
      }).then(function (res) {}).finally(function () {
        return Drupal.cartFlyout.fetchCarts();
      });
    },
    render: function render() {
      var template = Drupal.cartFlyout.getTemplate({
        id: 'commerce_cart_flyout_offcanvas',
        data: Drupal.cartFlyout.templates.offcanvas
      });
      this.$el.html(template.render({
        count: this.model.getCount(),
        links: this.model.getLinks()
      }));
      var contents = new Drupal.cartFlyout.CartContentsView({
        el: this.$el.find('.cart-block--offcanvas-contents__items'),
        model: this.model
      });
      contents.render();
    }
  });
  Drupal.cartFlyout.CartContentsView = Backbone.View.extend({
    render: function render() {

      var template = Drupal.cartFlyout.getTemplate({
        id: 'commerce_cart_flyout_offcanvas_contents',
        data: Drupal.cartFlyout.templates.offcanvas_contents
      });
      this.$el.html(template.render({
        carts: this.model.getCarts()
      }));

      this.$el.find('[data-cart-contents]').each(function () {
        var contents = new Drupal.cartFlyout.CartContentsItemsView({
          el: this,
          model: Drupal.cartFlyout.model
        });
        contents.render();
      });
    }
  });
  Drupal.cartFlyout.CartContentsItemsView = Backbone.View.extend({
    cart: {},
    initialize: function initialize() {
      this.cart = this.$el.data('cart-contents');
    },

    events: {
      'change .cart-block--offcanvas-cart-table__quantity input[type="number"]': 'onQuantityChange',
      'click .cart-block--offcanvas-contents__update': 'updateCart'
    },
    onQuantityChange: function onQuantityChange(e) {
      var targetDelta = e.target.dataset.key;
      var value = e.target.value;
      this.cart.order_items[targetDelta].quantity = parseInt(value);
    },
    updateCart: function updateCart(event) {
      event.preventDefault();
      var endpoint = Drupal.url('cart/' + this.cart.order_id + '/items?_format=json');
      fetch(endpoint, {
        credentials: 'include',
        headers: {
          'Accept': 'application/json',
          'Content-Type': 'application/json'
        },

        method: 'PATCH',
        body: JSON.stringify(this.cart.order_items)
      }).then(function (res) {}).finally(function () {
        return Drupal.cartFlyout.fetchCarts();
      });
    },
    render: function render() {
      var template = Drupal.cartFlyout.getTemplate({
        id: 'commerce_cart_flyout_offcanvas_contents_items',
        data: '        <table class="cart-block--offcanvas-cart-table table">' + '         <tbody>\n' + '        <% _.each(cart.order_items, function(orderItem, key) { %>' + '            <tr>\n' + '              <td class="cart-block--offcanvas-cart-table__title"><%- orderItem.title %></td>\n' + '              <td class="cart-block--offcanvas-cart-table__quantity">' + '                <input type="number" data-key="<% print(key) %>" value="<% print(parseInt(orderItem.quantity)) %>" style="width: 35px" />' + '              </td>\n' + '              <td class="cart-block--offcanvas-cart-table__price"><%= orderItem.total_price.formatted %></td>\n' + '              <td class="cart-block--offcanvas-cart-table__remove"><button value="<% print(JSON.stringify([cart.order_id, orderItem.order_item_id]))  %>" class="button btn">x</button></td>' + '            </tr>\n' + '        <% }); %>' + '          </tbody>\n' + '          <tfoot>' + '<td/>' + '<td colspan="3"><button type="submit" class="cart-block--offcanvas-contents__update button btn btn-primary">Update quantities</button></td>' + '          </tfoot>' + '        </table>\n'
      });
      this.$el.html(template.render({
        cart: this.cart
      }));
    }
  });
})(Backbone, Drupal);